function K = turn_kinds()
%TURN_KINDS 旋回の種類ごとの形(左に曲がるとして、入る向きは +y。右は x を反転して描く)。
%   entry: 前のオフセットを測り始める点、exit: 後ろのオフセットの後に着くはずの点、exit_dir: 出る向き
%   start: slalom_test で尻当ての後に記録を始める位置(区画の真ん中)
%   pillar_y0: 柱の y の並び(x は 90 + 180i)
%   adj: params.h の調整分の名前(前, 後ろ)
K.s90 = struct('label', '小回り 90°', 'angle', 90.0, 'entry', [0 0], 'exit', [-90 90], ...
    'exit_dir', [-1 0], 'start', [0 -270], 'pillar_y0', 0.0, ...
    'adj', {{'SLALOM_PRE_ADJ_MM', 'SLALOM_POST_ADJ_MM'}});
K.l90 = struct('label', '大回り 90°', 'angle', 90.0, 'entry', [0 0], 'exit', [-180 180], ...
    'exit_dir', [-1 0], 'start', [0 -180], 'pillar_y0', 90.0, ...
    'adj', {{'FAST_LARGE90_PRE_ADJ_MM', 'FAST_LARGE90_POST_ADJ_MM'}});
K.l180 = struct('label', '大回り 180°', 'angle', 180.0, 'entry', [0 0], 'exit', [-180 0], ...
    'exit_dir', [0 -1], 'start', [0 -180], 'pillar_y0', 90.0, ...
    'adj', {{'FAST_LARGE180_PRE_ADJ_MM', 'FAST_LARGE180_POST_ADJ_MM'}});
end
